[package]
name = "bridge"
version = "0.1.0"
authors = ["Vincent Isambart <vincent.isambart@gmail.com>"]

[dependencies]
clang = { version = "0.18", features = ["runtime", "clang_4_0"] }
quote = "0.3"
tempfile = "2.2"
