[package]
name = "chocolatier"
version = "0.1.0"
authors = ["Vincent Isambart <vincent.isambart@gmail.com>"]

[dependencies]
clang = { version = "0.18", features = ["runtime", "clang_5_0"] }
quote = "0.3.15"
tempfile = "2.2"
regex = "0.2.6"
lazy_static = "1.0"
nom = "4.0.0-beta1"
